### ISSUE TITLE
Minimum Stability DEV on install

### ISSUE THREAD

**Issue by bartolije** [redjanym/FCMBundle#1]
Hye,

Is there any symfony3 upgrade possible?
Trying to install, got this issue

`   - redjanym/fcm-bundle 1.0.1 requires sngrl/php-firebase-cloud-messaging dev-master -> satisfiable by sngrl/php-firebase-cloud-messaging[dev-master] but these conflict with your requirements or minimum-stability.`

EDIT: Not sure if totally related to s3

**Comment by redjanym** [comment]
Hi,
the bundle is not tested in Symfony3 but very soon i will be working to make it fully compatible if there is any issue. Although in my opinion should work with no problem. 
The problem you are having is not Symfony3 related, but it depends on the `minimum-stability` setting on your composer configuration of the project. By default requires only `stable` packages. One of my dependencies is not on a `stable` version.
Modify your project's `composer.json` file by adding this 2 lines:

``` json
minimum-stability: "dev",
prefer-stable: true
```

**Comment by bartolije** [comment]
I got it.

Thanks for the tips, and sorry for the non-related issue.

**Comment by Zuhayer** [comment]
Had the same issue. Thanks for the solution.

P.s. Awaiting Symfony3 compatibility

**Comment by redjanym** [comment]
Hi @Zuhayer, the bundle should be fully compatible with Symfony 3. The only bug it had was fixed in this issue: #2 

Happy coding :)
