### ISSUE TITLE
Send silent notification

### ISSUE THREAD

**Issue by Boulboulouboule** [redjanym/FCMBundle#10]
I would like to send silent notifications with this bundle, is it possible?

According to the Firebase documentation, it is possible to send this type of notification by entering the data field, leaving the notification field blank.

Only when I try to leave this field blank, firebase finds me an error:

![image](https://user-images.githubusercontent.com/5747750/26880849-0e9303b8-4b96-11e7-8b03-4c245a8c0a60.png)

This error seems to come from the fact that the bundle sets the notification field in all cases, even when I leave its initialization empty:

My code
```php
         $notification = $fcmClient->createDeviceNotification();
         $notification->setDeviceToken($target);
         $notification->setData([
                'title' => $title,
                'content' => $content,
         ]);
````
The bundle's code that seems problematical
```php
    /**
     * @param DeviceNotification | TopicNotification $notification
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function sendNotification($notification)
    {
        if (!$notification instanceof DeviceNotification && !$notification instanceof TopicNotification) {
            throw new \InvalidArgumentException('Notification must be of type DeviceNotification or TopicNotification');
        }

        $message = (new Message())
            ->setNotification($notification) // Adding some condition on that line should fix the issue
            ->setData($notification->getData())
            ->setPriority($notification->getPriority());

        // Check for the type of Notification
        if($notification instanceof DeviceNotification){
            foreach ($notification->getDeviceTokens() as $deviceToken) {
                $message->addRecipient(new Device($deviceToken));
            }
        } else if ($notification instanceof TopicNotification) {
            $message->addRecipient(new Topic($notification->getTopic()));
        }

        return $this->client->send($message);
    }
```

**Comment by Boulboulouboule** [comment]
This solve my issue. I use it like this : 

```php
    public function _sendSilentPushNotification($data, $target)
    {
        $fcmClient = $this->get('redjan_ym_fcm.client');

        $notification = $fcmClient->createDeviceNotification(null, null, $target);

        $notification->setData($data);
        $notification->setContentAvailable(true);

        $fcmClient->sendSilentNotification($notification);
    }
```

**Comment by redjanym** [comment]
Hello @Boulboulouboule,
thank you for notifying about this problem. The `content_available` argument solves the case according to Firebase. 
If you like you can add this assignment:

`php
      $message = (new Message())
            ->setContentAvailable($notification->getContentAvailable());
` 

on the existing `sendNotification` method of the `FCMClient` service and provide a PR. So this new functionality can be provided dynamically on the existing features. 
Thank you :)

**Comment by Boulboulouboule** [comment]
Hello @redjanym!

I first tried to configure the content_available to false (according to the firebase documentation), but it did not work as expected.

In my case, I had to send data messages without the notification field (https://firebase.google.com/docs/cloud-messaging/concept-options).

This can be properly added to the bundle by adding an optional argument to the sendPushNotification function, which if set, sends the message without the notification field.

It's ok for you ?

**Comment by redjanym** [comment]
It looks good to me. Just one thing, the PR please send it in the Develop branch. 
Thanks

**Comment by redjanym** [comment]
ping :)

**Comment by zluiten** [comment]
Since strictly speaking the notification payload is optional (https://firebase.google.com/docs/cloud-messaging/http-server-ref#table1), the notification key should not be serialized when empty.

I need this as well. I'll create a PR tomorrow.

**Comment by zluiten** [comment]
I've create a PR here https://github.com/redjanym/php-firebase-cloud-messaging/pull/3.

**Comment by redjanym** [comment]
Thanks @netiul. Merged and deployed in a new version.
