### ISSUE TITLE
How to check the result of sendNotification

### ISSUE THREAD

**Issue by faheemhameed** [redjanym/FCMBundle#18]
Hi there,

I would like to know how to read the result of the following function to see the notification was successful.

`$fcmClient->sendNotification($notification);
`

Many thanks.

**Comment by redjanym** [comment]
Hello @faheemhameed 
The `$fcmClient->sendNotification($notification);` returns an object as a response. If you do a var_dump of the response you will see all the info returned. 
Here is an example of checking it the notification is was sent or failed https://github.com/redjanym/FCMBundle/issues/9#issuecomment-295686177

Hope it helps.

**Comment by faheemhameed** [comment]
Hi @redjanym,

Thanks for your quick response. That helped me a lot!!

Regards,
Hameed
