### ISSUE TITLE
Services YAML parsing

### ISSUE THREAD

**Issue by bartolije** [redjanym/FCMBundle#2]
Hello,

I got an error.
In your `services.yml` file, you need to quote parameter.

```
    redjan_ym_fcm.client:
        class: RedjanYm\FCMBundle\FCMClient
        arguments: ['@sngrl.firebase_php_notification']
```

Else, I got this error.

```
 [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  The file "C:\xampp\htdocs\volvo\vendor\redjanym\fcm-bundle\DependencyInject
  ion/../Resources/config\services.yml" does not contain valid YAML.



  [Symfony\Component\Yaml\Exception\ParseException]
  The reserved indicator "@" cannot start a plain scalar; you need to quote t
  he scalar at line 4 (near "arguments: [@sngrl.firebase_php_notification]").

```

**Comment by redjanym** [comment]
Hi @bartolije ,
i believe this is a problem with Symfony 3 compatibility. If you can please provide a PR by forking the repo otherwise i will do it asap.  
Thanks

**Comment by bartolije** [comment]
Hello,

I did it in PR #3 
EDIT: Please note that I didn't tested it on Symfony2.

**Comment by redjanym** [comment]
Thanks @bartolije , i will test it and make a release this weekend along with support for Topic Notifications and very soon for Group Notifications ;)

**Comment by bartolije** [comment]
You rock.
Thanks a lots
