### ISSUE TITLE
How to send data message instead of notification message

### ISSUE THREAD

**Issue by jithin-pits** [redjanym/FCMBundle#26]
There are two types of message, notification message and data message, how to send data message

https://firebase.google.com/docs/cloud-messaging/concept-options

Please check the code we use:

$notification = $fcmClient->createDeviceNotification('', $json, $token);
$fcmClient->sendNotification($notification);

**Comment by jithin-pits** [comment]
Guys, we figured it out,

use 
$notification = $fcmClient->createDeviceNotification(null, null, $token);
$notification->setData($dataArray);
$fcmClient->sendNotification($notification);

**Comment by redjanym** [comment]
Hello @jithin-pits, yes that is the correct way to send a Data Message. 
I'm closing the issue. 
Happy coding :)
