### ISSUE TITLE
Attempted to load class "RedjanYmFCMBundle" from namespace "RedjanYm\FCMBundle".

### ISSUE THREAD

**Issue by bodva** [redjanym/FCMBundle#29]
Hello!

I've tried to install this bundle and have the error:

```
Attempted to load class "RedjanYmFCMBundle" from namespace "RedjanYm\FCMBundle".
Did you forget a "use" statement for another namespace?
```

Do you have any ideas why I expecting this error in my application?

**Comment by redjanym** [comment]
Hello @bodva , can you give me more details about your installation please?
1- Symfony verison
2- Have you followed the steps in the installation guide?
https://github.com/redjanym/FCMBundle/wiki/Installation

Please paste here:
1- composer line where ```redjanym/fcm-bundle``` is included
2- AppKernel.php 
3- config.yml 

Thanks

**Comment by bodva** [comment]
Hello @redjanym 
Thank you for the fast answer. I figured out already my problem. It's something caused specific of Docker container of this application.
