### ISSUE TITLE
Hot to work this bundle in symfony 4.4 ? 

### ISSUE THREAD

**Issue by crownbackend** [redjanym/FCMBundle#33]
Hey i have problème, i can use you bundle because I don’t know how to declare a service

`
Cannot autowire service "App\Manager\FCM\FCMClient": argument "$fcmClient" of method "__construct()" references class "RedjanYm\FCMBundle\FCMClient" but no such service exists. You should maybe alias this class to the existing "redjan_ym_fcm.client" service.`

i have délcare this in service.yaml 

`services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    notification.factory:
        class: App\Manager\FCM\NotificationFactory

    fcm.client:
        class: App\Manager\FCM\FCMClient
        arguments: [ "@redjan_ym_fcm.client", '%firebase_api_key%' ]

    App\Manager\FCM\FCMManager:
        arguments: [ "@fcm.client", "@notification.factory", "@serializer", "@doctrine.orm.entity_manager" ]`

**Comment by redjanym** [comment]
Hi. Check the reply on closed issue #32 
Let me know if that works for you.

**Comment by crownbackend** [comment]
Hey, thanks for your quick reply! I already set the yaml configuration but it doesn’t work, it displays the following error message:
`Cannot autowire service "App\Manager\FCM\FCMClient": argument "$fcmClient" of method "__construct()" references class "RedjanYm\FCMBundle\FCMClient" but no such service exists. You should maybe alias this class to the existing "redjan_ym_fcm.client" service.`

**Comment by redjanym** [comment]
Can you restore everything in the state it was before creating the custom services you did in the first comment and make a clean installation? 
Also try to remove the cache manually and rebuild it. It should work because i currently use it on a Symfony 4.4 project with just that minimal configuration.

**Comment by crownbackend** [comment]
I’ve already deleted the cache and I need my personal layer to be able to send notifications, which I don’t understand is why he tells me he can’t find a service? because I’m declaring it here:

`<?php

namespace App\Manager\FCM;

class FCMClient
{
    /**
     * @var FCMClient
     */
    private $fcmClient;

    /**
     * @var string
     */
    private $firebase_api_key_hardware;

    public function __construct(\RedjanYm\FCMBundle\FCMClient $fcmClient, string $firebase_api_key_hardware)
    {
        $this->fcmClient = $fcmClient;
        $this->firebase_api_key_hardware = $firebase_api_key_hardware;
    }

    public function getFcmClient()
    {
        return $this->fcmClient;
    }

    public function changeApiKeyForHardware()
    {
        $this->changeApiKey($this->firebase_api_key_hardware);
    }

    public function changeApiKey(string $apiKey)
    {
        $fcmClientReflection = new \ReflectionClass(get_class($this->fcmClient));

        $clientReflection = $fcmClientReflection->getProperty('client');
        $clientReflection->setAccessible(true);

        ($clientReflection->getValue($this->fcmClient))->setApiKey($apiKey);
    }
}
`

**Comment by redjanym** [comment]
Have you tried to rename your class? Also, since you are passing the $firebase_api_key_hardware parameter you need to declare it in your services.yml file. Can i see it?

**Comment by crownbackend** [comment]
I already change the name it does not work! and my token i lest declare well in the paramters party of my services.yaml

**Comment by redjanym** [comment]
I don't know what specifically might be wrong. In order to have a better view of the situation and i could also replicate it pls copy&paste here the service declaration and the your custom service(is has changed from the above version). Otherwise i won't be able to be of much help.

**Comment by redjanym** [comment]
@crownbackend  in case your are still having problems. Now this bundle is added as a Symfony Recipe. So if you do a fresh install of the bundle, the configurations will be done automatically and all you need to do is to set the correct value of the FCM_SERVER_KEY env variable.
