### ISSUE TITLE
How to set click_action on the notification

### ISSUE THREAD

**Issue by cesarZubillaga** [redjanym/FCMBundle#5]
I need to set this params for the notifications:

white_icon
default
MainActivity

On the sendNotification method of RedjanYm\FCMBundle\FCMClient on the $message->setNotification we are passing as argument a sngrl\PhpFirebaseCloudMessaging\Notification with title and body on the constructor. I dont see how to set those extra params.

On my project i have created a new service extending the FCMClient  and altering the sendNotification method so i can set those values:

    /**
     * @param DeviceNotification | TopicNotification $notification
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function sendNotification($notification)
    {
        if (!$notification instanceof DeviceNotification && !$notification instanceof TopicNotification) {
            throw new \InvalidArgumentException('Notification must be of type DeviceNotification or TopicNotification');
        }

        $message = new Message();
        $message->setPriority($notification->getPriority());

        // Check for the type of Notification
        if($notification instanceof DeviceNotification){
            $message->addRecipient(new Device($notification->getDeviceToken()));
        } else if ($notification instanceof TopicNotification) {
            $message->addRecipient(new Topic($notification->getTopic()));
        }
        $_notification = new Notification(
            $notification->getTitle(),
            $notification->getBody()
        );
        $_notification->setIcon('white_icon');
        $_notification->setSound('default');
        $_notification->setClickAction('MainActivity');

        $message
            ->setNotification(
                $_notification
            )
            ->setData($notification->getData());

        return $this->_client->send($message);
    }

¿There's any solution to this problem?

Thanks a lot!

**Comment by redjanym** [comment]
Hello, 
thank you for letting me know about the issue. 
I will provide all the missing properties on my  `\RedjanYm\FCMBundle\Entity\Notification` entity asap.

**Comment by redjanym** [comment]
Issue fixed :)

**Comment by cesarZubillaga** [comment]
Thanks a lot!
