### ISSUE TITLE
Allow multiple tokens

### ISSUE THREAD

**Issue by marcosangiovanni** [redjanym/FCMBundle#7]
sendNotification allows sending only to one recipient.
$message->addRecipient(new Device($notification->getDeviceToken()));
addRecipient allows to add devices to an array.

**Comment by redjanym** [comment]
Hi @marcosangiovanni, 
thank you for letting me know about the issue. I will add the support for multiple tokens ASAP.

**Comment by tobemedia** [comment]
+1
I also need multiple tokens. 
Let me know if I should implement and create a PullRequest

**Comment by redjanym** [comment]
The feature is on the way :)

**Comment by redjanym** [comment]
@tobemedia you are welcomed to provide a PR. I will gladly evaluate it

**Comment by redjanym** [comment]
Hi guys,
sorry for the long wait. I added the support for multiple device tokens in Device Notifications. This feature was not supported in the https://github.com/redjanym/php-firebase-cloud-messaging library so i added it. 
Please update the package and in the new version you will find the new helper methods to add additional tokens. 

Regards
