### ISSUE TITLE
Send notification with invalid device token

### ISSUE THREAD

**Issue by NewOldMax** [redjanym/FCMBundle#9]
Hi,

Lets look at example:
- user installed app, app sends token to backend and all are happy
- user reinstalled app, app sends new token to backend

I should remove old token, because it's invalid for now, but how I can know, which token is invalid?
When i'll send a notification with invalid token, what response i'll get?

**Comment by NewOldMax** [comment]
Nevermind, I just test it. :)
````php
$response = $this->fcmClient->sendNotification($notification);
$content = json_decode($response->getBody()->getContents());
if ($content->failure) {
    //do stuff
}
````

**Comment by redjanym** [comment]
Hi :)
Sorry i haven't had the time to check. But i'm glad you figured it out :)
I confirm that this is the correct way to check the token validity in the case of a Single Device Notification, but in case of Topic or Group Notification you get a report with the number of notifications sent or not. In that case is not much of a help to check the validity. 
If you have any suggestion, please share :)

**Comment by NewOldMax** [comment]
For now I see only one solution for Topic/Group notifications.
Run by cron job some command which will send a test notification (with `dry_run = true`) for every single token and check response.

**Comment by redjanym** [comment]
Hi,
i think the best way would be to check the validity of the Token at the moment you try to send the notification(the dry_run won't stop the notification sending to the end user and this is a bad UX). Check the response and if it is invalid then start a process to delete that Token from the User(or other entities) where it is attached. I know this might cause a delay in the process of sending notifications or in the UX but this can also be solved. Drop me an email at ymerajr@yahoo.com in case you need to discuss it in more details.
